### ISSUE TITLE
Legacy python syntax cause import error

### ISSUE THREAD

**Issue by Th3R3g3nt** [EnableSecurity/Identity-Crisis#1]
Line 242 causes compile error because of the following error:
SyntaxError: ("'with' will become a reserved keyword in Python 2.6", ('path:\identitycrisis.py', 242, 8, ''))
Platform: Win7 x64 (yeah yeah... I know....)
Python: 2.7.8
Java: 1.8.0_45-b14

Exact line:
with open(customheadersfn,'r') as customheadersf:

Suggested correction (with indentation correction):
customheadersf = open(customheadersfn,'r')

**Comment by sandrogauci** [comment]
Can you tell me which Jython version you are using please?
Note that you'll need to make use of version 2.7 or greater rather than Jython 2.5.

**Comment by Th3R3g3nt** [comment]
Sorry for the late response.
Jython 2.5.3

So this answered my question... :) If anyone else is having this, just do the change above & enjoy this fine plugin! :+1:
